require_relative 'binary_search_tree'

first = Node.new("The Matrix", 87)
btree = BinarySearchTree.new(first) 
pacific_rim = Node.new("Pacific Rim", 72) 
braveheart = Node.new("Braveheart", 78) 
jedi = Node.new("Star Wars: Return of the Jedi", 80)
donnie = Node.new("Donnie Darko", 85)
inception = Node.new("Inception", 86)
district = Node.new("District 9", 90)
shawshank = Node.new("The Shawshank Redemption", 91)
martian = Node.new("The Martian", 92)
hope = Node.new("Star Wars: A New Hope", 93)
empire = Node.new("Star Wars: The Empire Strikes Back", 94)
mad_max_2 = Node.new("Mad Max 2: The Road Warrior", 98)

btree.insert(btree.root, pacific_rim)
btree.insert(btree.root, braveheart)
btree.insert(btree.root, jedi)
btree.insert(btree.root, donnie)
btree.insert(btree.root, inception)
btree.insert(btree.root, district)
btree.insert(btree.root, shawshank)
btree.insert(btree.root, martian)
btree.insert(btree.root, hope)
btree.insert(btree.root, empire)
btree.insert(btree.root, mad_max_2)

btree.printf()

btree.delete(btree.root, pacific_rim.title)